name: Build Docker Images

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2.0.0

      # https://github.com/docker/metadata-action#tags-input

      - name: Docker version meta
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: mceachen/test
          flavor: |
            latest=false
          tags: |
            type=semver,pattern={{version}}

      - name: Docker :alpha meta
        id: meta-alpha
        uses: docker/metadata-action@v4.0.1
        if: contains(github.ref_name, 'alpha')
        with:
          images: mceachen/test
          flavor: |
            latest=false
          tags: |
            type=raw,value=alpha

      - name: Docker :beta meta
        id: meta-beta
        uses: docker/metadata-action@v4.0.1
        if: contains(github.ref_name, 'beta')
        with:
          images: mceachen/test
          flavor: |
            latest=false
          tags: |
            # Tag :beta with :alpha so testers don't have to change their config
            type=raw,value=alpha
            type=raw,value=beta

      - name: Docker :stable meta
        id: meta-stable
        uses: docker/metadata-action@v4.0.1
        if: ${{ !contains(github.ref_name, 'alpha') && !contains(github.ref_name, 'beta') }}
        with:
          images: mceachen/test
          tags: |
            # Tag stable with :alpha and :beta so testers always get the latest
            type=raw,value=alpha
            type=raw,value=beta
            type=raw,value=stable
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.0.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build and push
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }} ${{ steps.meta-alpha.outputs.tags }} ${{ steps.meta-beta.outputs.tags }} ${{ steps.meta-stable.outputs.tags }}
